### ISSUE TITLE
Добавить структуру и оглавление

### ISSUE THREAD

**Issue by citrux** [pinecrew/philosophy#1]
Выделить заголовки, добавить якоря и вставить в README оглавление со ссылочками

**Comment by FreeCX** [comment]
Начал делать в #2

**Comment by FreeCX** [comment]
Осталось только оглавление в README перенести

**Comment by citrux** [comment]
Я думаю, что оглавление в README переносить не стоит; можно просто добавить ссылку на этот текст после вопросов. Ответы на вопросы нужнее этой книги, я ведь думал, что она целиком по вопросам, а оказалось, что нет.

**Comment by FreeCX** [comment]
Закрываем тогда?
